from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response
from sqlalchemy.orm import Session

from .. import database, models, pdf, rbac, security

router = APIRouter(prefix="/documents", tags=["Documents"])


def _student(db: Session, student_user_id: int, current_user: models.User) -> models.User:
    student = db.query(models.User).filter(models.User.id == student_user_id, models.User.role == models.UserRole.STUDENT).first()
    if not student or not student.student_profile:
        raise HTTPException(status_code=404, detail="Student not found")
    if current_user.school_id and student.school_id != current_user.school_id:
        raise HTTPException(status_code=403, detail="Student belongs to another school")
    return student


@router.get("/verify/{document_type}/{document_id}")
def verify_document(document_type: str, document_id: int, db: Session = Depends(database.get_db)):
    if document_type == "receipt":
        payment = db.query(models.Payment).filter(models.Payment.id == document_id).first()
        if not payment:
            raise HTTPException(status_code=404, detail="Document not found")
        return {"valid": True, "document_type": document_type, "document_id": document_id, "reference": payment.receipt_number, "issued_at": payment.payment_date}
    if document_type == "certificate":
        cert = db.query(models.CertificateRequest).filter(models.CertificateRequest.id == document_id).first()
        if not cert:
            raise HTTPException(status_code=404, detail="Document not found")
        return {"valid": cert.status != models.CertificateStatus.BLOCKED, "document_type": document_type, "document_id": document_id, "reference": f"CERT-{cert.id}", "issued_at": cert.generated_at}
    if document_type == "diploma":
        diploma = db.query(models.DiplomaRecord).filter(models.DiplomaRecord.id == document_id).first()
        if not diploma:
            raise HTTPException(status_code=404, detail="Document not found")
        return {"valid": diploma.is_certified, "document_type": document_type, "document_id": document_id, "reference": diploma.certificate_number, "issued_at": diploma.issued_date}
    raise HTTPException(status_code=404, detail="Unsupported document type")


@router.get("/students/{student_user_id}/receipt/{payment_id}.pdf")
def payment_receipt_pdf(student_user_id: int, payment_id: int, db: Session = Depends(database.get_db), current_user: models.User = Depends(security.get_current_user)):
    rbac.require_permission(current_user, "documents:receipt")
    student = _student(db, student_user_id, current_user)
    payment = db.query(models.Payment).join(models.Fee).filter(models.Payment.id == payment_id, models.Fee.student_id == student.student_profile.id).first()
    if not payment:
        raise HTTPException(status_code=404, detail="Payment not found")
    lines = [
        f"Student: {student.full_name}",
        f"Matricule: {student.student_profile.registration_number}",
        f"Fee: {payment.fee.title}",
        f"Receipt: {payment.receipt_number}",
        f"Amount: {payment.amount:,.0f} {student.school.default_currency if student.school else 'FCFA'}",
        f"Date: {payment.payment_date}",
        f"Operator: {payment.recorded_by.full_name if payment.recorded_by else '-'}",
        f"Locale: {student.school.primary_language if student.school else 'fr'} / {student.school.timezone if student.school else 'Africa/Abidjan'}",
        f"Verification: /documents/verify/receipt/{payment.id}",
        f"QR payload: VERIFY:receipt:{payment.id}:{payment.receipt_number}",
    ]
    return Response(pdf.professional_pdf("Recu de paiement", lines, f"VERIFY:receipt:{payment.id}:{payment.receipt_number}"), media_type="application/pdf")


@router.get("/students/{student_user_id}/certificate/{certificate_id}.pdf")
def certificate_pdf(student_user_id: int, certificate_id: int, db: Session = Depends(database.get_db), current_user: models.User = Depends(security.get_current_user)):
    rbac.require_permission(current_user, "documents:issue")
    student = _student(db, student_user_id, current_user)
    cert = db.query(models.CertificateRequest).filter(models.CertificateRequest.id == certificate_id, models.CertificateRequest.student_id == student.student_profile.id).first()
    if not cert:
        raise HTTPException(status_code=404, detail="Certificate not found")
    if cert.status == models.CertificateStatus.BLOCKED:
        raise HTTPException(status_code=400, detail=cert.blocked_reason or "Certificate is blocked")
    lines = [
        f"Student: {student.full_name}",
        f"Matricule: {student.student_profile.registration_number}",
        f"Type: {cert.certificate_type.value}",
        f"Country: {student.school.country_code if student.school else '-'}",
        cert.content or "Certificate generated by school administration.",
        f"Generated at: {cert.generated_at}",
        f"Verification: /documents/verify/certificate/{cert.id}",
        f"QR payload: VERIFY:certificate:{cert.id}:CERT-{cert.id}",
    ]
    return Response(pdf.professional_pdf("Attestation", lines, f"VERIFY:certificate:{cert.id}:CERT-{cert.id}"), media_type="application/pdf")


@router.get("/students/{student_user_id}/report-card.pdf")
def report_card_pdf(student_user_id: int, db: Session = Depends(database.get_db), current_user: models.User = Depends(security.get_current_user)):
    rbac.require_permission(current_user, "reports:read")
    student = _student(db, student_user_id, current_user)
    grades = db.query(models.Grade).filter(models.Grade.student_id == student.student_profile.id).all()
    lines = [
        f"Student: {student.full_name}",
        f"Matricule: {student.student_profile.registration_number}",
        f"Class: {student.student_profile.current_class.name if student.student_profile.current_class else '-'}",
        f"Locale: {student.school.primary_language if student.school else 'fr'}",
        "",
    ]
    if grades:
        for grade in grades:
            assessment = grade.assessment
            lines.append(f"{assessment.subject.name if assessment and assessment.subject else '-'} / {assessment.title if assessment else '-'}: {grade.score}")
    else:
        lines.append("No grades recorded.")
    return Response(pdf.professional_pdf("Bulletin scolaire", lines, f"VERIFY:report-card:{student.student_profile.id}:{student.student_profile.registration_number}"), media_type="application/pdf")


@router.get("/diplomas/{diploma_id}.pdf")
def diploma_pdf(diploma_id: int, db: Session = Depends(database.get_db), current_user: models.User = Depends(security.get_current_user)):
    rbac.require_permission(current_user, "documents:issue")
    query = db.query(models.DiplomaRecord).filter(models.DiplomaRecord.id == diploma_id)
    if current_user.school_id:
        query = query.filter(models.DiplomaRecord.school_id == current_user.school_id)
    diploma = query.first()
    if not diploma:
        raise HTTPException(status_code=404, detail="Diploma not found")
    student = diploma.student.user if diploma.student and diploma.student.user else None
    lines = [
        f"Student: {student.full_name if student else '-'}",
        f"Diploma: {diploma.diploma_name}",
        f"Mention: {diploma.mention or '-'}",
        f"Certificate number: {diploma.certificate_number}",
        f"Credits: {diploma.total_credits}",
        f"Issued date: {diploma.issued_date}",
        f"Certified: {'yes' if diploma.is_certified else 'no'}",
        f"Verification: /documents/verify/diploma/{diploma.id}",
        f"QR payload: VERIFY:diploma:{diploma.id}:{diploma.certificate_number}",
    ]
    return Response(pdf.professional_pdf("Diplome certifie", lines, f"VERIFY:diploma:{diploma.id}:{diploma.certificate_number}"), media_type="application/pdf")
