const TRANSLATIONS: Record<string, Record<string, string>> = {
  "AI Agent": { fr: "Agent IA", es: "Agente IA", sw: "Wakala wa IA" },
  Actions: { fr: "Actions", es: "Acciones", sw: "Vitendo" },
  Active: { fr: "Actif", es: "Activo", sw: "Hai" },
  "Add Admissions": { fr: "Ajouter une admission", es: "Agregar admision", sw: "Ongeza udahili" },
  "Add Canteen": { fr: "Ajouter une cantine", es: "Agregar comedor", sw: "Ongeza kantini" },
  "Add Exams": { fr: "Ajouter un examen", es: "Agregar examen", sw: "Ongeza mtihani" },
  "Add Fee": { fr: "Ajouter des frais", es: "Agregar cuota", sw: "Ongeza ada" },
  "Add Fee Rubric": { fr: "Ajouter une rubrique de frais", es: "Agregar rubrica de cuota", sw: "Ongeza kipengele cha ada" },
  "Add Forecast": { fr: "Ajouter un previsionnel", es: "Agregar prevision", sw: "Ongeza utabiri" },
  "Add Payroll": { fr: "Ajouter une paie", es: "Agregar nomina", sw: "Ongeza malipo" },
  Add: { fr: "Ajouter", es: "Agregar", sw: "Ongeza" },
  "Add Teacher": { fr: "Ajouter un enseignant", es: "Agregar docente", sw: "Ongeza mwalimu" },
  "Add Student": { fr: "Ajouter un eleve", es: "Agregar estudiante", sw: "Ongeza mwanafunzi" },
  Address: { fr: "Adresse", es: "Direccion", sw: "Anwani" },
  Admissions: { fr: "Admissions", es: "Admisiones", sw: "Udahili" },
  Apply: { fr: "Appliquer", es: "Aplicar", sw: "Tumia" },
  "Applicant name": { fr: "Nom du candidat", es: "Nombre del candidato", sw: "Jina la mwombaji" },
  Author: { fr: "Auteur", es: "Autor", sw: "Mwandishi" },
  "By Class": { fr: "Par classe", es: "Por clase", sw: "Kwa darasa" },
  "By Fee Type": { fr: "Par type de frais", es: "Por tipo de cuota", sw: "Kwa aina ya ada" },
  "By Operator": { fr: "Par operateur", es: "Por operador", sw: "Kwa mhudumu" },
  "Canteen List": { fr: "Liste cantine", es: "Lista comedor", sw: "Orodha ya kantini" },
  Canteen: { fr: "Cantine", es: "Comedor", sw: "Kantini" },
  Book: { fr: "Livre", es: "Libro", sw: "Kitabu" },
  "Borrower (Student)": { fr: "Emprunteur (eleve)", es: "Prestatario (estudiante)", sw: "Mkopaji (mwanafunzi)" },
  Cancel: { fr: "Annuler", es: "Cancelar", sw: "Ghairi" },
  Category: { fr: "Categorie", es: "Categoria", sw: "Kategoria" },
  Class: { fr: "Classe", es: "Clase", sw: "Darasa" },
  "Class ID": { fr: "ID classe", es: "ID clase", sw: "Kitambulisho cha darasa" },
  Close: { fr: "Fermer", es: "Cerrar", sw: "Funga" },
  Collected: { fr: "Encaisse", es: "Cobrado", sw: "Iliyokusanywa" },
  "Configured Rubrics": { fr: "Rubriques configurees", es: "Rubricas configuradas", sw: "Vipengele vilivyowekwa" },
  "Copy Amounts": { fr: "Copier les montants", es: "Copiar importes", sw: "Nakili kiasi" },
  "Copy Previous Year": { fr: "Copier l'annee precedente", es: "Copiar ano anterior", sw: "Nakili mwaka uliopita" },
  "Create Accounts": { fr: "Creer des comptes", es: "Crear cuentas", sw: "Unda akaunti" },
  "Create Approvals": { fr: "Creer des validations", es: "Crear aprobaciones", sw: "Unda idhini" },
  "Create Canteen Subscriptions": { fr: "Creer des abonnements cantine", es: "Crear suscripciones comedor", sw: "Unda usajili wa kantini" },
  "Create Government Exports": { fr: "Creer des exports officiels", es: "Crear exportaciones oficiales", sw: "Unda mauzo rasmi ya data" },
  "Create Leaves": { fr: "Creer des conges", es: "Crear permisos", sw: "Unda likizo" },
  "Create Notification Providers": { fr: "Creer des fournisseurs de notification", es: "Crear proveedores de notificacion", sw: "Unda watoa arifa" },
  "Create Transcripts": { fr: "Creer des releves", es: "Crear certificados de notas", sw: "Unda nakala za matokeo" },
  "Create University Schedule": { fr: "Creer un emploi du temps universitaire", es: "Crear horario universitario", sw: "Unda ratiba ya chuo" },
  Date: { fr: "Date", es: "Fecha", sw: "Tarehe" },
  "Date of Birth": { fr: "Date de naissance", es: "Fecha de nacimiento", sw: "Tarehe ya kuzaliwa" },
  Debtors: { fr: "Debiteurs", es: "Deudores", sw: "Wadaiwa" },
  Delete: { fr: "Supprimer", es: "Eliminar", sw: "Futa" },
  Description: { fr: "Description", es: "Descripcion", sw: "Maelezo" },
  "Desired level": { fr: "Niveau souhaite", es: "Nivel deseado", sw: "Ngazi inayotakiwa" },
  Diplomas: { fr: "Diplomes", es: "Diplomas", sw: "Stashahada" },
  "Due Date": { fr: "Date d'echeance", es: "Fecha limite", sw: "Tarehe ya mwisho" },
  Edit: { fr: "Modifier", es: "Editar", sw: "Hariri" },
  Email: { fr: "Email", es: "Correo", sw: "Barua pepe" },
  "Entity ID": { fr: "ID entite", es: "ID entidad", sw: "Kitambulisho cha chombo" },
  "Entity type": { fr: "Type d'entite", es: "Tipo de entidad", sw: "Aina ya chombo" },
  Expected: { fr: "Attendu", es: "Esperado", sw: "Inayotarajiwa" },
  "Expected revenue": { fr: "Recette attendue", es: "Ingreso esperado", sw: "Mapato yanayotarajiwa" },
  "Expected students": { fr: "Effectif attendu", es: "Estudiantes esperados", sw: "Wanafunzi wanaotarajiwa" },
  "Export type": { fr: "Type d'export", es: "Tipo de exportacion", sw: "Aina ya usafirishaji" },
  "Fee category": { fr: "Categorie de frais", es: "Categoria de cuota", sw: "Kategoria ya ada" },
  "Fee Settings": { fr: "Parametrage des frais", es: "Configuracion de cuotas", sw: "Mipangilio ya ada" },
  "Finance Reports": { fr: "Rapports financiers", es: "Informes financieros", sw: "Ripoti za fedha" },
  Forecasts: { fr: "Previsionnels", es: "Previsiones", sw: "Utabiri" },
  "Full Name": { fr: "Nom complet", es: "Nombre completo", sw: "Jina kamili" },
  Gender: { fr: "Genre", es: "Genero", sw: "Jinsia" },
  "Gross": { fr: "Brut", es: "Bruto", sw: "Jumla" },
  "Inspection": { fr: "Inspection", es: "Inspeccion", sw: "Ukaguzi" },
  "Institution Operations": { fr: "Operations de l'etablissement", es: "Operaciones de la institucion", sw: "Shughuli za taasisi" },
  "Journal Total": { fr: "Total journal", es: "Total diario", sw: "Jumla ya jarida" },
  Level: { fr: "Niveau", es: "Nivel", sw: "Ngazi" },
  Location: { fr: "Emplacement", es: "Ubicacion", sw: "Mahali" },
  "Location / Shelf": { fr: "Emplacement / rayon", es: "Ubicacion / estante", sw: "Mahali / rafu" },
  "Low Stock": { fr: "Stock bas", es: "Stock bajo", sw: "Akiba ndogo" },
  "LMD / ECTS": { fr: "LMD / ECTS", es: "LMD / ECTS", sw: "LMD / ECTS" },
  Message: { fr: "Message", es: "Mensaje", sw: "Ujumbe" },
  Name: { fr: "Nom", es: "Nombre", sw: "Jina" },
  Notifications: { fr: "Notifications", es: "Notificaciones", sw: "Arifa" },
  Notes: { fr: "Notes", es: "Notas", sw: "Maelezo" },
  "Notes (Optional)": { fr: "Notes (facultatif)", es: "Notas (opcional)", sw: "Maelezo (hiari)" },
  Optional: { fr: "Facultatif", es: "Opcional", sw: "Hiari" },
  Outstanding: { fr: "Impayes", es: "Pendiente", sw: "Deni" },
  "Operator ID": { fr: "ID operateur", es: "ID operador", sw: "Kitambulisho cha mhudumu" },
  otp: { fr: "Code MFA / 2FA", es: "Codigo MFA / 2FA", sw: "Msimbo MFA / 2FA" },
  Password: { fr: "Mot de passe", es: "Contrasena", sw: "Nenosiri" },
  Period: { fr: "Periode", es: "Periodo", sw: "Kipindi" },
  "Pending": { fr: "En attente", es: "Pendiente", sw: "Inasubiri" },
  "Pending Approvals": { fr: "Validations en attente", es: "Aprobaciones pendientes", sw: "Idhini zinazosubiri" },
  Phone: { fr: "Telephone", es: "Telefono", sw: "Simu" },
  Print: { fr: "Imprimer", es: "Imprimir", sw: "Chapisha" },
  "Program ID": { fr: "ID programme", es: "ID programa", sw: "Kitambulisho cha programu" },
  Programs: { fr: "Programmes", es: "Programas", sw: "Programu" },
  Quantity: { fr: "Quantite", es: "Cantidad", sw: "Idadi" },
  "Queue Message": { fr: "Mettre le message en file", es: "Encolar mensaje", sw: "Weka ujumbe kwenye foleni" },
  "Queue SMS": { fr: "Mettre le SMS en file", es: "Encolar SMS", sw: "Weka SMS kwenye foleni" },
  "Receipt": { fr: "Recu", es: "Recibo", sw: "Risiti" },
  Refresh: { fr: "Actualiser", es: "Actualizar", sw: "Onyesha upya" },
  Remaining: { fr: "Restant", es: "Restante", sw: "Iliyobaki" },
  "Save Attendance": { fr: "Enregistrer la presence", es: "Guardar asistencia", sw: "Hifadhi mahudhurio" },
  "Save Changes": { fr: "Enregistrer les modifications", es: "Guardar cambios", sw: "Hifadhi mabadiliko" },
  "Save Grades": { fr: "Enregistrer les notes", es: "Guardar notas", sw: "Hifadhi alama" },
  "Save Teacher": { fr: "Enregistrer l'enseignant", es: "Guardar docente", sw: "Hifadhi mwalimu" },
  Save: { fr: "Enregistrer", es: "Guardar", sw: "Hifadhi" },
  "Saving...": { fr: "Enregistrement...", es: "Guardando...", sw: "Inahifadhi..." },
  Search: { fr: "Rechercher", es: "Buscar", sw: "Tafuta" },
  "Search assessments...": { fr: "Rechercher des evaluations...", es: "Buscar evaluaciones...", sw: "Tafuta tathmini..." },
  "Search books...": { fr: "Rechercher des livres...", es: "Buscar libros...", sw: "Tafuta vitabu..." },
  "Search expenses...": { fr: "Rechercher des depenses...", es: "Buscar gastos...", sw: "Tafuta matumizi..." },
  "Search loans...": { fr: "Rechercher des prets...", es: "Buscar prestamos...", sw: "Tafuta mikopo..." },
  "Search students...": { fr: "Rechercher des eleves...", es: "Buscar estudiantes...", sw: "Tafuta wanafunzi..." },
  "Search subjects...": { fr: "Rechercher des matieres...", es: "Buscar asignaturas...", sw: "Tafuta masomo..." },
  "Search teachers...": { fr: "Rechercher des enseignants...", es: "Buscar docentes...", sw: "Tafuta walimu..." },
  "Select Book": { fr: "Selectionner un livre", es: "Seleccionar libro", sw: "Chagua kitabu" },
  "Select Student": { fr: "Selectionner un eleve", es: "Seleccionar estudiante", sw: "Chagua mwanafunzi" },
  "Select class": { fr: "Selectionner une classe", es: "Seleccionar clase", sw: "Chagua darasa" },
  "Select subject": { fr: "Selectionner une matiere", es: "Seleccionar asignatura", sw: "Chagua somo" },
  "Select term": { fr: "Selectionner une periode", es: "Seleccionar periodo", sw: "Chagua muhula" },
  Status: { fr: "Statut", es: "Estado", sw: "Hali" },
  Student: { fr: "Eleve", es: "Estudiante", sw: "Mwanafunzi" },
  "Student profile ID": { fr: "ID profil eleve", es: "ID perfil estudiante", sw: "Kitambulisho cha mwanafunzi" },
  "Submit Closure": { fr: "Soumettre la cloture", es: "Enviar cierre", sw: "Wasilisha kufunga" },
  Subject: { fr: "Matiere", es: "Asignatura", sw: "Somo" },
  "Suspended": { fr: "Suspendu", es: "Suspendido", sw: "Imesimamishwa" },
  Teacher: { fr: "Enseignant", es: "Docente", sw: "Mwalimu" },
  Title: { fr: "Titre", es: "Titulo", sw: "Kichwa" },
  Transport: { fr: "Transport", es: "Transporte", sw: "Usafiri" },
  "Transport / Canteen": { fr: "Transport / Cantine", es: "Transporte / Comedor", sw: "Usafiri / Kantini" },
  Type: { fr: "Type", es: "Tipo", sw: "Aina" },
  Variance: { fr: "Ecart", es: "Variacion", sw: "Tofauti" },
}

const FIELD_HELP: Array<[RegExp, string]> = [
  [/date d'?echeance|due date/i, "Date d'echeance : elle sert a definir la date limite de paiement. Cette date est utilisee pour le suivi des paiements, des retards et des impayes."],
  [/message/i, "Message : saisissez le contenu exact a envoyer ou a enregistrer. Il sera visible dans l'historique des notifications et peut etre transmis aux destinataires autorises."],
  [/parent phone|telephone parent|telephone/i, "Telephone : indiquez un numero joignable au format attendu pour le pays. Il sert aux notifications, rappels, absences et urgences administratives."],
  [/parent name|nom parent/i, "Nom du parent : indiquez le nom complet du parent, tuteur ou representant legal. Cette information relie l'eleve a sa famille."],
  [/student profile id|id profil eleve/i, "ID profil eleve : identifiant interne de l'eleve concerne. Il permet de rattacher automatiquement paiements, documents et notifications au bon dossier."],
  [/amount|montant|price|gross|deductions|revenue/i, "Montant : saisissez une valeur numerique positive dans la devise de l'etablissement. Elle alimente la facturation, la caisse et les rapports financiers."],
  [/email/i, "Email : saisissez une adresse valide. Elle sert a l'authentification, aux notifications et a la communication officielle."],
  [/otp|mfa|2fa/i, "Code MFA / 2FA : saisissez le code temporaire genere par votre application d'authentification. Il renforce la securite du compte lors de la connexion."],
  [/password|mot de passe/i, "Mot de passe : saisissez une valeur confidentielle respectant la politique de securite. Elle protege l'acces au compte utilisateur."],
  [/class|classe/i, "Classe : selectionnez ou saisissez la classe concernee. Elle permet de filtrer les eleves, emplois du temps, notes, frais et rapports."],
  [/program|programme|filiere/i, "Programme : indiquez la filiere ou le programme concerne. Cette donnee structure les admissions, cours, diplomes et rapports academiques."],
  [/status|statut/i, "Statut : choisissez l'etat actuel de l'element. Il pilote les workflows, validations, filtres et actions autorisees."],
  [/name|nom|title|titre/i, "Nom ou titre : saisissez un libelle clair et unique. Il facilite la recherche, l'affichage dans les listes et la generation de documents."],
  [/description|notes/i, "Description : ajoutez les precisions utiles. Ces informations aident les utilisateurs autorises a comprendre le contexte et les decisions."],
]

export function currentLocale() {
  if (typeof window === "undefined") return "fr"
  const segment = window.location.pathname.split("/").filter(Boolean)[0]
  return ["fr", "en", "es", "sw"].includes(segment) ? segment : "fr"
}

export function localizeUiText(value: string | undefined | null, locale = currentLocale()) {
  if (!value) return value || ""
  const normalized = value.replace(/\s+\*/g, "").trim()
  const suffix = value.includes("*") ? " *" : ""
  if (locale === "en") return value
  return (TRANSLATIONS[normalized]?.[locale] || value) + (TRANSLATIONS[normalized]?.[locale] ? suffix : "")
}

export function helpForLabel(value: string | undefined | null) {
  const label = localizeUiText(value || "Ce champ").replace(/\s+\*/g, "").trim()
  const match = FIELD_HELP.find(([pattern]) => pattern.test(label) || pattern.test(value || ""))
  if (match) return match[1]
  return `${label}: saisissez une information exacte. Cette donnee est utilisee pour les controles, rapports, documents et actions autorisees selon votre role. Respectez le format indique par le champ.`
}
